-- Creora — production schema, captured 10 Aug 2026
--
-- Generated by running supabase/dump_schema.sql in the Supabase SQL Editor
-- against project "CREO". Until this file existed, the only copy of these
-- eight SECURITY DEFINER functions lived inside the Supabase dashboard.
--
-- Regenerate with:  supabase db dump > supabase/schemas/prod.sql
-- (see supabase/README.md for the one-time CLI setup)
--
-- ---------------------------------------------------------------------------
-- READ THIS BEFORE PUBLISHING ANYTHING
--
-- RLS is enabled on both tables and there are ZERO policies, so no role can
-- touch the tables directly. All access goes through the eight functions
-- below, which are SECURITY DEFINER — they run as the definer and bypass RLS.
--
-- Every one of those eight is granted to `anon`, and not one of them checks
-- who is calling. The anon key ships inside the browser bundle, so it is
-- public by design. Anyone holding it can therefore:
--
--   save_page(any id, ...)          overwrite any page in the database
--   get_page(any id)                read any page
--   list_pages()                    enumerate every page
--   create_page(...)                create pages
--   add_database_row(...)           insert rows into any database block
--   update_database_row(any id, …)  modify any row
--   delete_database_row(any id)     delete any row
--
-- The July RLS lockdown closed direct table access but left the RPC layer
-- open. There is no identity in the system at all — no supabase.auth call
-- exists anywhere in the codebase. Restrict these grants and add ownership
-- (Steps 3 and 4) before this is reachable by anyone but you.
--
-- Note also that database_rows has no page, project, or owner column. Rows
-- are scoped only by database_block_id, and deleting a block does not delete
-- its rows — deleteBlock in App.tsx has no delete_database_row call.
-- ---------------------------------------------------------------------------

-- ===== TABLES =====
CREATE TABLE IF NOT EXISTS public.database_rows (
  id text NOT NULL,
  database_block_id text NOT NULL,
  row_data jsonb DEFAULT '{}'::jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS public.pages (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  blocks jsonb DEFAULT '[]'::jsonb,
  workflows jsonb DEFAULT '[]'::jsonb,
  updated_at timestamp with time zone DEFAULT now()
);

-- ===== CONSTRAINTS =====
ALTER TABLE public.database_rows ADD CONSTRAINT database_rows_pkey PRIMARY KEY (id);

ALTER TABLE public.pages ADD CONSTRAINT pages_pkey PRIMARY KEY (id);

-- ===== INDEXES =====
CREATE INDEX idx_database_rows_block_id ON public.database_rows USING btree (database_block_id, created_at);

-- ===== ROW LEVEL SECURITY =====
ALTER TABLE public.database_rows ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.pages ENABLE ROW LEVEL SECURITY;

-- ===== POLICIES =====
-- (none — intentional. RLS with no policies denies all direct table access.)

-- ===== FUNCTIONS (RPC) =====
CREATE OR REPLACE FUNCTION public.add_database_row(p_id text, p_block_id text, p_row_data jsonb)
 RETURNS void
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  insert into public.database_rows (id, database_block_id, row_data) values (p_id, p_block_id, p_row_data);
$function$
;

CREATE OR REPLACE FUNCTION public.create_page(p_id uuid, p_blocks jsonb)
 RETURNS void
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  insert into public.pages (id, blocks, workflows) values (p_id, p_blocks, '[]'::jsonb);
$function$
;

CREATE OR REPLACE FUNCTION public.delete_database_row(p_id text)
 RETURNS void
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  delete from public.database_rows where id = p_id;
$function$
;

CREATE OR REPLACE FUNCTION public.get_page(p_id uuid)
 RETURNS TABLE(id uuid, blocks jsonb, workflows jsonb, updated_at timestamp with time zone)
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select id, blocks, workflows, updated_at from public.pages where id = p_id;
$function$
;

CREATE OR REPLACE FUNCTION public.list_database_rows(p_block_id text)
 RETURNS TABLE(id text, row_data jsonb, created_at timestamp with time zone)
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select id, row_data, created_at from public.database_rows
  where database_block_id = p_block_id order by created_at asc;
$function$
;

CREATE OR REPLACE FUNCTION public.list_pages()
 RETURNS TABLE(id uuid, page_name text)
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select id, coalesce(blocks->>'pageName', 'Untitled') from public.pages order by updated_at asc;
$function$
;

CREATE OR REPLACE FUNCTION public.save_page(p_id uuid, p_blocks jsonb, p_workflows jsonb)
 RETURNS void
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  update public.pages set blocks = p_blocks, workflows = p_workflows, updated_at = now() where id = p_id;
$function$
;

CREATE OR REPLACE FUNCTION public.update_database_row(p_id text, p_row_data jsonb)
 RETURNS void
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  update public.database_rows set row_data = p_row_data where id = p_id;
$function$
;

-- ===== GRANTS =====
-- Every grant below is the security gap described in the header.
GRANT EXECUTE ON FUNCTION public.add_database_row(p_id text, p_block_id text, p_row_data jsonb) TO anon;
GRANT EXECUTE ON FUNCTION public.add_database_row(p_id text, p_block_id text, p_row_data jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.add_database_row(p_id text, p_block_id text, p_row_data jsonb) TO service_role;

GRANT EXECUTE ON FUNCTION public.create_page(p_id uuid, p_blocks jsonb) TO anon;
GRANT EXECUTE ON FUNCTION public.create_page(p_id uuid, p_blocks jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.create_page(p_id uuid, p_blocks jsonb) TO service_role;

GRANT EXECUTE ON FUNCTION public.delete_database_row(p_id text) TO anon;
GRANT EXECUTE ON FUNCTION public.delete_database_row(p_id text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.delete_database_row(p_id text) TO service_role;

GRANT EXECUTE ON FUNCTION public.get_page(p_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.get_page(p_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_page(p_id uuid) TO service_role;

GRANT EXECUTE ON FUNCTION public.list_database_rows(p_block_id text) TO anon;
GRANT EXECUTE ON FUNCTION public.list_database_rows(p_block_id text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.list_database_rows(p_block_id text) TO service_role;

GRANT EXECUTE ON FUNCTION public.list_pages() TO anon;
GRANT EXECUTE ON FUNCTION public.list_pages() TO authenticated;
GRANT EXECUTE ON FUNCTION public.list_pages() TO service_role;

GRANT EXECUTE ON FUNCTION public.save_page(p_id uuid, p_blocks jsonb, p_workflows jsonb) TO anon;
GRANT EXECUTE ON FUNCTION public.save_page(p_id uuid, p_blocks jsonb, p_workflows jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.save_page(p_id uuid, p_blocks jsonb, p_workflows jsonb) TO service_role;

GRANT EXECUTE ON FUNCTION public.update_database_row(p_id text, p_row_data jsonb) TO anon;
GRANT EXECUTE ON FUNCTION public.update_database_row(p_id text, p_row_data jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.update_database_row(p_id text, p_row_data jsonb) TO service_role;
