import { Node } from '@tiptap/core';
import { ReactNodeViewRenderer, NodeViewWrapper } from '@tiptap/react';
import type { NodeViewProps } from '@tiptap/react';
import { useAtomValue, useSetAtom, useStore } from 'jotai';
import { useMemo, useRef, useState, useEffect, useCallback } from 'react';
import {
  blockRuntimeAtom,
  activeWireAtom,
  snapTargetAtom,
  triggerSaveAtom,
  contextMenuAtom,
  getPortBadge,
  getBlockTypeDisplayName,
  isPreviewModeAtom,
} from '../state/atoms';
import { useBlockDrag } from '../hooks/useBlockDrag';
import { blockToCSS } from '../lib/renderBlockStyles';
import { sanitizeHtml, findSlots, fillSlots } from '../lib/sanitizeHtml';
import { useSlotValues } from '../lib/useSlotValues';
import { useDatabaseRows } from '../hooks/useDatabaseRows';
import { visibleRows, rowSlots } from '../lib/rows';
import { executeWorkflow, recalculateAllFormulas } from '../lib/bindingEngine';

/**
 * For each row: one piece of markup, repeated.
 *
 * WHY THIS IS THE UNLOCK
 * Everything Creora could show until now was a fixed shape somebody here chose:
 * a table that looks like our table, a list that looks like our list. A blog, a
 * directory, a gallery, a leaderboard and a set of search results are all the
 * same thing -- rows, laid out however the builder wants -- and none of them
 * were expressible.
 *
 * The template is the builder's own markup with {{Column}} slots in it, run
 * through the same sanitiser as the My Design block. So a card designed in
 * Figma, generated by an AI, or lifted off a site they liked, becomes a
 * repeating card driven by real rows. That is the Lego idea: they bring the
 * design, Creora attaches the data behind it.
 *
 * ONE VIEW, TWO PLACES
 * RepeatView is exported and used by both the editor block and the published
 * renderer, for the same reason CustomHtmlView is: a repeater that shows
 * something different once published is worse than no repeater.
 */

function pagerButtonStyle(disabled: boolean): React.CSSProperties {
  return {
    padding: '6px 12px',
    borderRadius: '6px',
    border: '1px solid #cbd5e1',
    background: disabled ? '#f1f5f9' : '#ffffff',
    color: disabled ? '#94a3b8' : '#0f172a',
    cursor: disabled ? 'default' : 'pointer',
    fontSize: '13px',
  };
}

export function RepeatView({
  blockId,
  poll = false,
  interactive = true,
}: {
  blockId: string;
  poll?: boolean;
  interactive?: boolean;
}) {
  const store = useStore();
  const state = useAtomValue(blockRuntimeAtom(blockId));
  const { rows, isLoading, error } = useDatabaseRows(state?.trackedBlockId, poll);

  /**
   * The four controls a visitor can be holding.
   *
   * Read unconditionally, with an empty id standing in for "not wired", so the
   * number of hooks never changes between renders. A hook behind an `if` is a
   * hook that fires in a different order the moment a builder picks a search box.
   */
  const searchState = useAtomValue(blockRuntimeAtom(state?.searchBlockId || ''));
  const filterState = useAtomValue(blockRuntimeAtom(state?.filterBlockId || ''));
  const sortColumnState = useAtomValue(blockRuntimeAtom(state?.sortColumnBlockId || ''));
  const sortDirectionState = useAtomValue(blockRuntimeAtom(state?.sortDirectionBlockId || ''));

  const searchText = state?.searchBlockId ? String(searchState?.value ?? '') : '';
  // A live filter value wins over the fixed one, so a builder can set a sensible
  // default in the panel and still let a visitor change it.
  const filterValue = state?.filterBlockId ? filterState?.value : state?.filterValue;
  const sortColumn = state?.sortColumnBlockId
    ? String(sortColumnState?.value ?? '') || undefined
    : state?.sortColumn;
  const sortDirection = state?.sortDirectionBlockId
    ? (sortDirectionState?.value ? 'desc' : 'asc')
    : state?.sortDirection;

  const [page, setPage] = useState(1);

  /**
   * Back to page one whenever what is being looked at changes.
   *
   * Without this, searching while on page 4 of the old results shows an empty
   * page, and every visitor reads that as "no results" rather than "wrong page".
   * It is the classic paging bug and it is one line.
   */
  useEffect(() => {
    setPage(1);
  }, [searchText, filterValue, sortColumn, sortDirection, state?.pageSize]);

  const view = useMemo(
    () =>
      visibleRows(rows, {
        search: searchText,
        searchColumns: state?.searchColumns,
        filterColumn: state?.filterColumn,
        filterOperator: state?.filterOperator,
        filterValue,
        sortColumn,
        sortDirection,
        page,
        pageSize: state?.pageSize,
        maxRows: state?.maxRows,
      }),
    [
      rows,
      searchText,
      state?.searchColumns,
      state?.filterColumn,
      state?.filterOperator,
      filterValue,
      sortColumn,
      sortDirection,
      page,
      state?.pageSize,
      state?.maxRows,
    ]
  );
  const template = useMemo(() => sanitizeHtml(state?.rowHtml), [state?.rowHtml]);
  const empty = useMemo(() => sanitizeHtml(state?.emptyHtml), [state?.emptyHtml]);

  // Slots the template uses that are not columns fall back to blocks on the
  // page by name, so a card can show "{{Search}}" or a title from a Text block
  // without that being a separate feature.
  const templateSlots = useMemo(() => findSlots(template.html), [template.html]);
  const pageValues = useSlotValues(templateSlots);

  const clickColumn = state?.clickColumn;
  const rowsAreClickable = interactive && !!clickColumn;

  const onRowClick = useCallback(
    (row: Record<string, any>) => {
      if (!clickColumn) return;
      const picked = clickColumn === 'Row id' ? row?.id : row?.[clickColumn];
      const current = store.get(blockRuntimeAtom(blockId));
      store.set(blockRuntimeAtom(blockId), {
        ...current,
        value: picked === undefined || picked === null ? '' : picked,
      });
      // onClick rather than onChange: pressing a card is a press. The value is
      // already updated by the time anything wired to it runs, so a workflow
      // reading this block sees the row that was actually clicked.
      executeWorkflow(blockId, 'onClick', store);
      recalculateAllFormulas(store);
    },
    [blockId, clickColumn, store]
  );

  const gap = state?.gap ?? 12;
  const containerStyle: React.CSSProperties =
    state?.layout === 'grid'
      ? {
          display: 'grid',
          gridTemplateColumns: `repeat(${Math.max(1, state?.gridColumns ?? 3)}, minmax(0, 1fr))`,
          gap: `${gap}px`,
        }
      : { display: 'flex', flexDirection: 'column', gap: `${gap}px` };

  if (!state?.trackedBlockId) {
    return (
      <div style={{ fontSize: '12px', color: '#64748b', fontFamily: 'sans-serif' }}>
        Pick a Database in the panel, and this repeats your markup once per row.
      </div>
    );
  }

  if (error) {
    return (
      <div style={{ fontSize: '12px', color: '#b91c1c', fontFamily: 'sans-serif' }}>{error}</div>
    );
  }

  if (isLoading) {
    return (
      <div style={{ fontSize: '12px', color: '#94a3b8', fontFamily: 'sans-serif' }}>Loading…</div>
    );
  }

  if (view.rows.length === 0) {
    // An empty list that shows nothing at all reads as broken. It has to say so.
    return <div dangerouslySetInnerHTML={{ __html: empty.html }} />;
  }

  return (
    <div>
      <div style={containerStyle}>
        {view.rows.map((row, index) => {
          const html = fillSlots(
            template.html,
            { ...pageValues, ...rowSlots(row, index) },
            template.urlSlots
          );
          return (
            <div
              key={row?.id ?? index}
              onClick={rowsAreClickable ? () => onRowClick(row) : undefined}
              style={rowsAreClickable ? { cursor: 'pointer' } : undefined}
              dangerouslySetInnerHTML={{ __html: html }}
            />
          );
        })}
      </div>
      {view.truncatedNote && (
        <div style={{ marginTop: '8px', fontSize: '11px', color: '#64748b', fontFamily: 'sans-serif' }}>
          {view.truncatedNote}
        </div>
      )}

      {/*
        The built-in pager, switchable off. A builder who wants their own
        buttons should not have to hide ours: the page number is ordinary state
        and two buttons wired to it do the same job.
      */}
      {state?.showPager !== false && view.pageCount > 1 && (
        <div
          style={{
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between',
            gap: '8px',
            marginTop: gap + 'px',
            fontFamily: 'sans-serif',
            fontSize: '13px',
          }}
        >
          <button
            type="button"
            disabled={view.page <= 1}
            onClick={() => setPage((p) => Math.max(1, p - 1))}
            style={pagerButtonStyle(view.page <= 1)}
          >
            {state?.prevLabel || 'Previous'}
          </button>
          <span style={{ color: '#64748b' }}>
            Page {view.page} of {view.pageCount}
          </span>
          <button
            type="button"
            disabled={view.page >= view.pageCount}
            onClick={() => setPage((p) => p + 1)}
            style={pagerButtonStyle(view.page >= view.pageCount)}
          >
            {state?.nextLabel || 'Next'}
          </button>
        </div>
      )}
    </div>
  );
}

const RepeatBlockComponent = (props: NodeViewProps) => {
  const { node } = props;
  const { blockId } = node.attrs;
  const store = useStore();
  const [isHovered, setIsHovered] = useState(false);
  const setActiveWire = useSetAtom(activeWireAtom);
  const snapTarget = useAtomValue(snapTargetAtom);
  const setContextMenu = useSetAtom(contextMenuAtom);
  const isPreviewMode = useAtomValue(isPreviewModeAtom);
  const triggerSave = useSetAtom(triggerSaveAtom);

  const atomInstance = useMemo(() => blockRuntimeAtom(blockId), [blockId]);
  const runtimeState = useAtomValue(atomInstance, { store });

  const containerRef = useRef<HTMLElement | null>(null);
  if (!containerRef.current) containerRef.current = document.getElementById('editor-container');

  const wrapperRef = useRef<HTMLDivElement | null>(null);
  const { position, handlePointerDown, handlePointerMove, handlePointerUp } = useBlockDrag(
    blockId,
    containerRef as React.RefObject<HTMLElement>
  );

  const handleContextMenu = useCallback((e: MouseEvent) => {
    e.preventDefault();
    e.stopPropagation();
    e.stopImmediatePropagation();
    if (isPreviewMode) return;
    const c = containerRef.current;
    if (!c) return;
    const r = c.getBoundingClientRect();
    setContextMenu({ blockId, x: e.clientX - r.left, y: e.clientY - r.top, visible: true });
  }, [blockId, setContextMenu, isPreviewMode]);

  useEffect(() => {
    const el = wrapperRef.current;
    if (!el) return;
    el.addEventListener('contextmenu', handleContextMenu, true);
    return () => el.removeEventListener('contextmenu', handleContextMenu, true);
  }, [handleContextMenu]);

  const onOutputPortPointerDown = (e: React.PointerEvent) => {
    e.stopPropagation();
    const c = containerRef.current;
    if (!c) return;
    const cr = c.getBoundingClientRect();
    const pr = (e.currentTarget as HTMLElement).getBoundingClientRect();
    const x = pr.left + pr.width / 2 - cr.left;
    const y = pr.top + pr.height / 2 - cr.top;
    setActiveWire({ sourceBlockId: blockId, sourceX: x, sourceY: y, currentX: x, currentY: y });
  };

  const isSnapTarget = snapTarget === blockId;
  const showPorts = (isHovered || isSnapTarget) && !isPreviewMode;
  // `inner` carries the builder's own CSS, so custom styling reaches a
  // repeater the same way it reaches every other block. A default is a
  // starting point, never a ceiling.
  const { outer: outerStyle, inner: innerStyle } = blockToCSS('repeatBlock', position, runtimeState);

  return (
    <NodeViewWrapper
      as="div"
      ref={wrapperRef as any}
      className="repeat-block-wrapper"
      style={{ ...outerStyle, cursor: 'move', width: (runtimeState?.width ?? 360) + 'px' }}
      onPointerDown={handlePointerDown}
      onPointerMove={handlePointerMove}
      onPointerUp={(e: React.PointerEvent) => {
        handlePointerUp(e);
        triggerSave((prev) => prev + 1);
      }}
      onMouseEnter={() => setIsHovered(true)}
      onMouseLeave={() => setIsHovered(false)}
    >
      <div style={{ position: 'absolute', top: '-16px', left: 0, fontSize: '10px', opacity: 0.6, color: '#cbd5e1', userSelect: 'none', fontWeight: 500, whiteSpace: 'nowrap' }}>
        {runtimeState?.blockName || getBlockTypeDisplayName('repeatBlock')}
      </div>

      {/* Rows are inert in the editor: a click there means "select this block",
          not "run whatever this row is wired to". Preview is where it runs. */}
      <div contentEditable={false} style={innerStyle}>
        <RepeatView blockId={blockId} interactive={isPreviewMode} />
      </div>

      <div
        contentEditable={false}
        data-port-input={blockId}
        style={{
          position: 'absolute',
          left: '-5px',
          top: '20px',
          width: '10px',
          height: '10px',
          borderRadius: '50%',
          backgroundColor: '#22c55e',
          border: '2px solid white',
          boxShadow: isSnapTarget ? '0 0 8px 2px #22c55e' : 'none',
          opacity: showPorts ? 1 : 0,
          pointerEvents: showPorts ? ('all' as const) : ('none' as const),
          transition: 'opacity 0.15s',
        }}
      />

      <div
        contentEditable={false}
        data-port-output={blockId}
        onPointerDown={onOutputPortPointerDown}
        style={{
          position: 'absolute',
          right: '-5px',
          top: '20px',
          width: '10px',
          height: '10px',
          borderRadius: '50%',
          backgroundColor: '#6366f1',
          border: '2px solid white',
          opacity: showPorts ? 1 : 0,
          pointerEvents: showPorts ? ('all' as const) : ('none' as const),
          cursor: 'crosshair',
          transition: 'opacity 0.15s',
        }}
      >
        <span style={{ position: 'absolute', right: '12px', top: '50%', transform: 'translateY(-50%)', fontSize: '10px', fontWeight: 'bold', color: '#6366f1', pointerEvents: 'none', userSelect: 'none' }}>
          {getPortBadge('string')}
        </span>
      </div>
    </NodeViewWrapper>
  );
};

export const RepeatBlock = Node.create({
  name: 'repeatBlock',
  group: 'block',
  atom: true,
  selectable: true,

  addAttributes() {
    return { blockId: { default: null } };
  },

  parseHTML() {
    return [{ tag: 'div[data-type="repeat-block"]' }];
  },

  renderHTML({ HTMLAttributes }) {
    return ['div', { ...HTMLAttributes, 'data-type': 'repeat-block' }];
  },

  addNodeView() {
    return ReactNodeViewRenderer(RepeatBlockComponent, { as: 'div' });
  },
});
